### PR TITLE
Update `vendor` submodule to latest commit

### PR DESCRIPTION
**Pull request by ok-nick**
The cause of great suffering.

### CODE REVIEW

**Comment by ssalonen** [comment]
CI run failed with Linux now. I remember having issues making  build work with vendored libcec6... 

BTW does v6 build with older compilers (is there anything in change log?). Ideally vendored is something conservative that works for many

Couple of things require attention in any case
- make sure vendor is matching to a tag, that is, a proper release 
- CI tests needs updating, as they explicitly test that vendored abi is v4. Should be easy enough to change by modifying github flow
- Readme refers to vendored libcec being v4, should be updated

**Comment by ok-nick** [comment]
I can't say for Linux, but for Windows, according to [this script](https://github.com/Pulse-Eight/libcec-support/blob/416da1d0e60ee2397f31d4eb8f85886a9ef3327a/windows/config/toolchain.cmd), it most likely works with older compilers? Probably the same compatibility for Linux then, I don't see anything in the changelog for it.

v4 is pretty old, and you must use <= Visual Studio 14 from 2015 to compile it on Windows. Not too conservative for us Windows users, definitely the best bet is to upgrade to v6.

**Comment by ok-nick** [comment]
That's weird, why does [this test](https://github.com/ok-nick/libcec-sys/blob/f8b94baf103a865025f0b8f51367a2f3d87fe783/.github/workflows/ci.yml#L84-L93) install v6 when v4 is specified?

**Comment by ok-nick** [comment]
It seems you can't specify a version for `libcec-dev`, and in new Ubuntu releases, it defaults to v6, [check here](https://packages.ubuntu.com/search?keywords=libcec&searchon=names&suite=all&section=all). I'm not familiar with Linux or how this should be handled, any ideas?

**Comment by ssalonen** [comment]
Thanks for noting this! You are probably right

It has been some months since the CI last run, ubuntu-latest must have changed in between.

Probably makes sense to introduce separate PR to fix the CI. Need to see whether we can keep some libcec4 tests there, it is still widely used?

**Comment by ok-nick** [comment]
I'm not sure if v4 is still used, but you're right. CI should probably run once for each version (to ensure all smoke tests work).

It says [here](https://github.com/Pulse-Eight/libcec/blob/76551ea1dd9a55f0ce1533e440dc12dbc594f7ba/debian/changelog.in#L182), in the changelog, that they renamed `libcec-dev` to `libcec4-dev`, so it looks like an easy fix.

**Comment by ssalonen** [comment]
I found some issues with `build.rs`: it was reusing a `cc_command` (of type `Command`), leading to unexpected issues. Fixed now in https://github.com/ssalonen/libcec-sys/pull/16 -- let's see if CI passes

**Comment by ssalonen** [comment]
Can you also change the `vendor` to refer to a `libcec-6.0.2` tag (commit 29d82c80bcc62be2878a9ac080de7eb286c4beb9)? Not it is referring to commit 76551ea1dd9a55f0ce1533e440dc12dbc594f7ba which is not a tag...

**Comment by ok-nick** [comment]
I ran the CI on my repo and it seems there are a few issues compiling vendored libcec v6.
https://github.com/ok-nick/libcec-sys/runs/7457424524?check_suite_focus=true#step:12:547

**Comment by ok-nick** [comment]
Looks good, should be ready to merge.

**Comment by ssalonen** [comment]
Thanks! Good stuff.

**Pull request merged**
